projects:
  socialapp-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: vni7k5licbfxje3i4ksqq7w5g4
        maxDepth: 10
extensions:
  amplify:
    version: 3
